theme: jekyll-theme-midnight
title: "SASS Frontend Lesson"
description: "SASS Frontend Lesson by Tirth, Jishnu, Yuri, Alan, and Haoxuan."
gitorg: "https://github.com/Tirth-Thakkar/MortaliciouslySassy"
google_analytics:
